const fs = require('fs');
let src = fs.readFileSync('admin/admin.js', 'utf8');

// Translate English labels to Ukrainian in PAGE_SCHEMA
const labelMap = {
    '"About Page Title"': '"SEO Title сторінки"',
    '"About Section Tag"': '"Тег розділу (мала позначка)"',
    '"Hero Title"': '"Головний заголовок"',
    '"About P1"': '"Основний опис клініки"',
    '"Nav Works"': '"Кнопка: Наші роботи"',
    '"Nav Services"': '"Кнопка: Послуги"',
    '"About Team Title"': '"Заголовок команди"',
    '"Team Savchuk Name"': '"Лікар 1: Ім\'я (Савчук)"',
    '"Team Savchuk Role"': '"Лікар 1: Посада (Савчук)"',
    '"Team Anatoliy Name"': '"Лікар 2: Ім\'я (Анатолій)"',
    '"Team Anatoliy Role"': '"Лікар 2: Посада (Анатолій)"',
    '"Team Mariya Name"': '"Лікар 3: Ім\'я (Марія)"',
    '"Team Mariya Role"': '"Лікар 3: Посада (Марія)"',
    '"Feat Aesthetic"': '"Фільтр: Естетична стоматологія"',
    '"Btn Book"': '"Кнопка: Записатися на консультацію"',
    '"Feat Therapy"': '"Фільтр: Лікування зубів"',
    '"Feat Surgery"': '"Фільтр: Хірургія"',
    '"Feat Ortho"': '"Фільтр: Ортодонтія"',
    '"Svc Consult Title"': '"Послуга: Консультація — Заголовок"',
    '"Svc Consult Desc"': '"Послуга: Консультація — Опис"',
    '"Price Consult General"': '"Ціна: Загальна консультація"',
    '"Btn Book Short"': '"Кнопка: Записатися (коротка)"',
    '"Price Consult Modjaw"': '"Ціна: Діагностика MODJAW"',
    '"Price Consult Checkup"': '"Ціна: CHECK-UP"',
    '"Svc Composite Veneer Title"': '"Послуга: Композитні вініри — Заголовок"',
    '"Svc Composite Veneer Desc"': '"Послуга: Композитні вініри — Опис"',
    '"Price Frontal Restoration"': '"Ціна: Реставрація фронтального зуба"',
    '"Price Art Restoration"': '"Ціна: Художня реставрація"',
    '"Svc Ceramic Restoration Title"': '"Послуга: Керамічні реставрації — Заголовок"',
    '"Svc Ceramic Restoration Desc"': '"Послуга: Керамічні реставрації — Опис"',
    '"Price Veneer Digital"': '"Ціна: Вінір (digital)"',
    '"Price Veneer Layering"': '"Ціна: Вінір (digital + нашарування)"',
    '"Price Veneer Handmade"': '"Ціна: Вінір (hand made)"',
    '"Price Veneer Rework"': '"Ціна: Переробка вініра"',
    '"Price Veneer Single"': '"Ціна: Вінір одиночний"',
    '"Price Crown Digital"': '"Ціна: Коронка (digital)"',
    '"Price Crown Layering"': '"Ціна: Коронка (digital + нашарування)"',
    '"Price Crown Handmade"': '"Ціна: Коронка (hand made)"',
    '"Svc Endo Title"': '"Послуга: Ендодонтія — Заголовок"',
    '"Svc Endo Desc"': '"Послуга: Ендодонтія — Опис"',
    '"Price Endo Incisor"': '"Ціна: Канали (різці, ікла)"',
    '"Price Endo Premolar"': '"Ціна: Канали (премоляри)"',
    '"Price Endo Molar"': '"Ціна: Канали (моляри)"',
    '"Svc Caries Title"': '"Послуга: Лікування карієсу — Заголовок"',
    '"Svc Caries Desc"': '"Послуга: Лікування карієсу — Опис"',
    '"Price Caries 2"': '"Ціна: Карієс II рівень"',
    '"Price Caries 3"': '"Ціна: Карієс III рівень"',
    '"Svc Periodontal Title"': '"Послуга: Пародонтологія — Заголовок"',
    '"Svc Periodontal Desc"': '"Послуга: Пародонтологія — Опис"',
    '"Price Periodont 1"': '"Ціна: Пародонтит I ступінь"',
    '"Price Periodont 2"': '"Ціна: Пародонтит II ступінь"',
    '"Price Periodont 3"': '"Ціна: Пародонтит III ступінь"',
    '"Svc Hygiene Title"': '"Послуга: Гігієна — Заголовок"',
    '"Svc Hygiene Desc"': '"Послуга: Гігієна — Опис"',
    '"Price Hygiene"': '"Ціна: Гігієна"',
    '"Price Hygiene Smoker"': '"Ціна: Гігієна (нальот курця)"',
    '"Svc Whitening Title"': '"Послуга: Відбілювання — Заголовок"',
    '"Svc Whitening Desc"': '"Послуга: Відбілювання — Опис"',
    '"Price Whitening"': '"Ціна: Відбілювання"',
    '"Svc Implant Title"': '"Послуга: Імплантація — Заголовок"',
    '"Svc Implant Desc"': '"Послуга: Імплантація — Опис"',
    '"Price Implant Neodent"': '"Ціна: Імплант NEODENT"',
    '"Price Implant Sla"': '"Ціна: Імплант STRAUMANN SLA"',
    '"Price Implant Slactive"': '"Ціна: Імплант STRAUMANN SLACTIVE"',
    '"Price Crown Monolit"': '"Ціна: Коронка (monolit)"',
    '"Price Crown Aesthetic"': '"Ціна: Коронка (ceramic + абатмент)"',
    '"Svc Extraction Title"': '"Послуга: Видалення зубів — Заголовок"',
    '"Svc Extraction Desc"': '"Послуга: Видалення зубів — Опис"',
    '"Price Extraction"': '"Ціна: Видалення зуба"',
    '"Price Extraction Atypical 1"': '"Ціна: Атипове видалення (просте)"',
    '"Price Extraction Atypical 2"': '"Ціна: Атипове видалення (складне)"',
    '"Price Sedation"': '"Ціна: Седація (1 година)"',
    '"Svc Gum Surgery Title"': '"Послуга: Хірургія ясен — Заголовок"',
    '"Svc Gum Surgery Desc"': '"Послуга: Хірургія ясен — Опис"',
    '"Price Gum Smile"': '"Ціна: Усунення ясеневої посмішки"',
    '"Price Recession"': '"Ціна: Закриття рецесій"',
    '"Price Gum Extension"': '"Ціна: Видовження ясен"',
    '"Svc Braces Title"': '"Послуга: Брекети — Заголовок"',
    '"Svc Braces Desc"': '"Послуга: Брекети — Опис"',
    '"Price Braces Metal"': '"Ціна: Брекети (метал)"',
    '"Price Braces Ceramic"': '"Ціна: Брекети (кераміка)"',
    '"Price Braces Self Metal"': '"Ціна: Самолігуючі (метал)"',
    '"Price Ortho Visit"': '"Ціна: Контрольний візит ортодонта"',
    '"Price Braces Self Ceramic"': '"Ціна: Самолігуючі (кераміка)"',
    '"Svc Aligners Title"': '"Послуга: Елайнери — Заголовок"',
    '"Svc Aligners Desc"': '"Послуга: Елайнери — Опис"',
    '"Price Aligners"': '"Ціна: Лікування елайнерами"',
    '"Form Name Placeholder"': '"Форма: Плейсхолдер імені"',
    '"Form Comment Placeholder"': '"Форма: Плейсхолдер коментаря"',
    '"Form Phone Placeholder"': '"Форма: Плейсхолдер телефону"',
    '"Form Privacy"': '"Форма: Текст приватності"',
    '"Form Btn"': '"Форма: Кнопка"',
    '"Cases Page Title"': '"SEO Title сторінки"',
    '"Cases Hero Title"': '"Головний заголовок"',
    '"Filter All"': '"Фільтр: Всі роботи"',
    '"Filter Veneers"': '"Фільтр: Керамічні вініри"',
    '"Filter Composite"': '"Фільтр: Композитні вініри"',
    '"Filter Restoration"': '"Фільтр: Композитні реставрації"',
    '"Filter Implants"': '"Фільтр: Імплантація"',
    '"Filter Ortho"': '"Фільтр: Ортодонтія"',
    '"Filter Whitening"': '"Фільтр: Відбілювання зубів"',
    '"Contacts Page Title"': '"SEO Title сторінки"',
    '"Form Title"': '"Форма: Заголовок"',
    '"Form Subtitle"': '"Форма: Підзаголовок"',
    '"Form Phone Label"': '"Форма: Телефон-лейбл"',
    '"Footer Find Us"': '"Де нас знайти"',
    '"Map Address"': '"Адреса клініки"',
    '"Footer Map Btn"': '"Кнопка: Знайти на карті"',
    '"Footer Hours Title"': '"Графік роботи: Заголовок"',
    '"Footer Hours Days"': '"Графік роботи: Години"',
    '"Footer Location"': '"Місто"',
    '"Footer Address Street"': '"Вулиця та номер"',
    '"Footer Map Btn"': '"Кнопка: Карта"',
    '"Footer Tagline"': '"Слоган (з емодзі)"',
    '"Footer Hours Title"': '"Графік: Заголовок"',
    '"Footer Hours Days"': '"Графік: Години роботи"',
    '"Footer Copyright"': '"Копірайт"',
    '"Btn Book"': '"Кнопка: Записатися"',
};

let count = 0;
for (const [eng, ukr] of Object.entries(labelMap)) {
    const pattern = `"label": ${eng}`;
    const replacement = `"label": ${ukr}`;
    if (src.includes(pattern)) {
        src = src.split(pattern).join(replacement);
        count++;
    }
}
console.log(`Translated ${count} labels`);

// Update version
src = src.replace(/v1\.0\.\d+/g, 'v1.0.7');
console.log('Version updated to v1.0.7');

fs.writeFileSync('admin/admin.js', src, 'utf8');
console.log('Done!');
